# Generated by Django 4.1.3 on 2022-12-08 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='datetime',
            new_name='date_time',
        ),
    ]
