# Generated by Django 4.1.4 on 2022-12-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_rename_datetime_price_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='volume',
            field=models.IntegerField(),
        ),
    ]
