# Specifies which syntax version of Docker compose
version: '3'

# Build a multiservice arhitecture.
services:
  # Create a service called web
  web:
    # Build an image from the files in the project root directory (Dockerfile)
    build: .
    # Assigns a name for the container. If no name is specified,
    # Docker will assign the container a random name
    container_name: drf_app
    # Mount the container `/drf` folder to the a `src` folder in the location
    # of the Dockerfile on the host machine.
    volumes:
      - ./src:/drf
    # Map port 8000 to port 9090 so that we can access the application on
    # our host machine by visiting 127.0.0.1:9090
    ports:
      - "9090:8000"
    depends_on:
      - database

  database:
    # Official Postgres image from DockerHub (we use the last version)
    image: 'postgres:latest'

    # By default, a Postgres database is running on the 5432 port.
    # If we want to access the database from our computer (outside the container),
    # we must share the port with our computer's port.
    # The syntax is [port we want on our machine]:[port we want to retrieve in the container]
    # Note: You are free to change your computer's port,
    # but take into consideration that it will change the way
    # you are connecting to your database.
    ports:
      - 5432:5432

    env_file:
      - /stock/.env

    environment:
      POSTGRES_USER: mujtaba # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: maz # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: default_database # The PostgreSQL default database (automatically created at first launch)