# Generated by Django 4.1.2 on 2022-12-07 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trader', '0001_initial'),
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('purchase', 'purchase'), ('sale', 'sale')], default='purchase', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('volume_transacted', models.FloatField()),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_prices', to='price.price')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_trader', to='trader.trader')),
            ],
        ),
    ]
