# Generated by Django 4.1.3 on 2022-12-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.ManyToManyField(blank=True, to='company.company')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
