# Generated by Django 4.1.2 on 2022-12-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('favourite', '0001_initial'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='trader', max_length=10)),
                ('mobile_number', models.CharField(default='0', max_length=20)),
                ('favourite', models.ManyToManyField(blank=True, to='favourite.favourite')),
                ('record', models.ManyToManyField(blank=True, to='transaction.transaction')),
            ],
        ),
    ]
