# Generated by Django 4.1.3 on 2022-12-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaction', '0001_initial'),
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='record',
            field=models.ManyToManyField(blank=True, to='transaction.transaction'),
        ),
    ]
