# Generated by Django 4.1.2 on 2022-12-07 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='role',
        ),
    ]
