# Generated by Django 4.1.3 on 2022-12-05 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('from_datetime', models.DateTimeField(default=0)),
                ('to_datetime', models.DateTimeField(default=0)),
                ('latest_prices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_price', to='price.price')),
                ('price', models.ManyToManyField(blank=True, to='price.price')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
