# Generated by Django 4.1.3 on 2022-11-30 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_price', to='price.price')),
            ],
        ),
    ]
