# Generated by Django 4.1.3 on 2022-12-05 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='from_datetime',
        ),
        migrations.RemoveField(
            model_name='company',
            name='to_datetime',
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_datetime', models.DateTimeField(default=0)),
                ('to_datetime', models.DateTimeField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_company', to='company.company')),
            ],
        ),
    ]
