# Generated by Django 4.1.3 on 2022-12-02 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['id']},
        ),
    ]
