# Generated by Django 4.1.2 on 2022-12-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_manager',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_trader',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'superuser'), ('trader', 'trader'), ('client', 'client')], default='client', max_length=10),
            preserve_default=False,
        ),
    ]
