# Generated by Django 4.1.2 on 2022-12-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='manager', max_length=10)),
                ('mobile_number', models.CharField(default='0', max_length=20)),
            ],
        ),
    ]
