# Generated by Django 4.1.3 on 2022-12-05 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_field', models.CharField(max_length=10)),
                ('minimum_limit', models.FloatField()),
                ('maximum_limit', models.FloatField()),
                ('trader_user_id', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_company', to='company.company')),
            ],
        ),
    ]
