# Generated by Django 4.1.4 on 2022-12-12 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_field', models.CharField(choices=[('ldcp', 'ldcp'), ('open', 'open'), ('high', 'high'), ('low', 'low'), ('current', 'current'), ('change', 'change'), ('volume', 'volume')], default='current', max_length=10)),
                ('minimum_limit', models.FloatField()),
                ('maximum_limit', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_company', to='company.company')),
            ],
        ),
    ]
