# Generated by Django 4.1.2 on 2022-12-07 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trader', '0001_initial'),
        ('favourite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_trader', to='trader.trader'),
        ),
    ]
