# Generated by Django 4.1.2 on 2022-12-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourite', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favourite',
            constraint=models.UniqueConstraint(fields=('company', 'trader', 'monitor_field', 'is_active'), name='unique_favourite'),
        ),
    ]
